# Dados

In [1]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
import cv2
import shutil
from module import data_read, setup
from torch.utils.data import ConcatDataset
from module.LightningModule import ClassificationModule
from module.setup import *
from module.data_read import *
from module.plot import imshow
from module import data_read
from torchvision import models
from torch import nn
import lightning as L
from lightning.pytorch.callbacks import Timer
from sklearn.model_selection import KFold
from lightning.pytorch.loggers import TensorBoardLogger

torch.manual_seed(random_state)
torch.set_float32_matmul_precision('high')

DDR_DIR = Path.cwd() / 'DDR-dataset/DR_grading'
IDRID_DIR = Path.cwd() / 'IDRID-Classificacao'

# Lighting Module

## Binary

In [2]:
def binary_train_and_test(model, model_name):

    anno_train_ddr = pd.read_csv(DDR_DIR/'train.txt', header=None, sep=' ')
    anno_train_ddr[0] = 'train/'+anno_train_ddr[0]
    anno_valid_ddr = pd.read_csv(DDR_DIR/'valid.txt', header=None, sep=' ')
    anno_valid_ddr[0] = 'valid/'+anno_valid_ddr[0]
    anno_test_ddr = pd.read_csv(DDR_DIR/'test.txt', header=None, sep=' ')
    anno_test_ddr[0] = 'test/'+anno_test_ddr[0]
    
    # Todas as anotações do DDR
    anno_ddr = pd.concat([anno_train_ddr, anno_valid_ddr, anno_test_ddr], ignore_index=True)
    kfold = KFold(n_splits=k_folds, shuffle=True, random_state=random_state)
    
    for fold, (train_ids, test_ids) in enumerate(kfold.split(anno_ddr)):
        print(f'FOLD {fold}')
        print('--------------------------------')
        
        # Divide os dados com base nos atuais indices do K-fold
        train_dataset = DDRDatasetKFold(DDR_DIR, anno_ddr.iloc[train_ids], data_transforms['train'], convert_to_binary=True, dataset_name='ddr')
        test_dataset = DDRDatasetKFold(DDR_DIR, anno_ddr.iloc[test_ids], data_transforms['test'], convert_to_binary=True, dataset_name='ddr')
    
    
        # Definição dos dataloaders
        trainloader = torch.utils.data.DataLoader(
                          train_dataset,
                          batch_size=batch_size,
                          shuffle=True,
                          num_workers=8) # MUDAR
        testloader = torch.utils.data.DataLoader(
                          test_dataset,
                          batch_size=batch_size,
                          shuffle=False,
                          num_workers=8)
        idridloader = torch.utils.data.DataLoader(
                          idrid_dataset,
                          batch_size=batch_size,
                          num_workers=8)
    
    
    
        logger = TensorBoardLogger(f'{CHECKPOINTS_DIR}/tb_logs', name=f"FOLD {fold} {model_name}")
        timer = Timer()
        # DEBUG:
        # trainer = L.Trainer(fast_dev_run=8, callbacks=[timer]) # a execução do trainer se limitará a fast_dev_run batchs
        # trainer = L.Trainer(limit_train_batches=50, max_epochs=1, default_root_dir='checkpoints_kfold/', logger=logger) # usar apenas essa % dos dados de cada lote de treino
    
        trainer = L.Trainer(accelerator='gpu', max_epochs=num_epochs, logger=logger, callbacks=[timer])
        
        # treino
        lmodel = ClassificationModule(model, loss_function, torch.optim.Adam, fold)
        trainer.fit(model=lmodel, train_dataloaders=trainloader)
        print(timer.time_elapsed("train"))
        
        # teste 
        trainer.test(model=lmodel, dataloaders=testloader) # test na fold de test
        print(timer.end_time("test"))
        trainer.test(model=lmodel, dataloaders=idridloader) # test no idrid
        print(timer.end_time("test")) 

In [3]:
# Leitura IDRID
train_idrid_dataset = IDRIDDataset(IDRID_DIR/'1. Original Images/a. Training Set',
                                   IDRID_DIR/'2. Groundtruths/a. IDRiD_Disease Grading_Training Labels.csv',
                                   data_transforms['test'],
                                   convert_to_binary=True,
                                   dataset_name='idrid')
test_idrid_dataset = IDRIDDataset(IDRID_DIR/'1. Original Images/b. Testing Set',
                                  IDRID_DIR/'2. Groundtruths/b. IDRiD_Disease Grading_Testing Labels.csv',                   
                                  data_transforms['test'],
                                  convert_to_binary=True,
                                  dataset_name='idrid')
idrid_dataset = ConcatDataset([train_idrid_dataset, test_idrid_dataset])

### VGG16 instanciation

In [3]:
# Transfer learning (fine tuning):
# Instanciação VGG16_BN
weights = models.VGG16_BN_Weights.DEFAULT # melhores pesos até o momento
vgg16 = models.vgg16_bn(weights=weights)
# transformações específicas da rede
vgg16_preprocess = weights.transforms()
# modificando a camada de classificação
num_ftrs = vgg16.classifier[-1].in_features
vgg16.classifier[-1] = nn.Linear(num_ftrs, num_classes)

In [4]:
vgg16_preprocess

ImageClassification(
    crop_size=[224]
    resize_size=[256]
    mean=[0.485, 0.456, 0.406]
    std=[0.229, 0.224, 0.225]
    interpolation=InterpolationMode.BILINEAR
)

In [5]:
vgg16.classifier

Sequential(
  (0): Linear(in_features=25088, out_features=4096, bias=True)
  (1): ReLU(inplace=True)
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=4096, out_features=4096, bias=True)
  (4): ReLU(inplace=True)
  (5): Dropout(p=0.5, inplace=False)
  (6): Linear(in_features=4096, out_features=2, bias=True)
)

In [6]:
binary_train_and_test(vgg16, 'vgg16_bn')

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 0
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


FOLD 0
--------------------------------



  | Name          | Type             | Params
---------------------------------------------------
0 | model         | VGG              | 134 M 
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
134 M     Trainable params
0         Non-trainable params
134 M     Total params
537.109   Total estimated model params size (MB)


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |                                                                                                    …

[[1086  173]
 [ 100 1149]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.8911483287811279
     ddr-test-aucroc        0.9580849409103394
       ddr-test-f1          0.8938156366348267
      ddr-test-loss         0.30523115396499634
   ddr-test-precision       0.8691376447677612
     ddr-test-recall         0.919935941696167
  ddr-test-specificity      0.8625893592834473
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |                                                                                                    …

[[ 42 126]
 [  0 348]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7558139562606812
    idrid-test-aucroc       0.9577261209487915
      idrid-test-f1         0.8467153310775757
     idrid-test-loss        1.0747910737991333
  idrid-test-precision      0.7341772317886353
    idrid-test-recall               1.0
 idrid-test-specificity            0.25
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 1
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | VGG              | 134 M 
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
134 M     Trainable params
0         Non-trainable params
134 M     Total params
537.109   Total estimated model params size (MB)


2740.0451954710006
240131.619944
FOLD 1
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |                                                                                                    …

[[1216   43]
 [ 164 1071]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.9170008301734924
     ddr-test-aucroc        0.9736665487289429
       ddr-test-f1          0.9118773937225342
      ddr-test-loss         0.21593543887138367
   ddr-test-precision       0.9614003300666809
     ddr-test-recall        0.8672064542770386
  ddr-test-specificity      0.9658458828926086
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |                                                                                                    …

[[ 50 118]
 [  0 348]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7713178396224976
    idrid-test-aucroc       0.9533815979957581
      idrid-test-f1         0.8550368547439575
     idrid-test-loss        0.9127195477485657
  idrid-test-precision      0.7467811107635498
    idrid-test-recall               1.0
 idrid-test-specificity     0.2976190447807312
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 2
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | VGG              | 134 M 
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
134 M     Trainable params
0         Non-trainable params
134 M     Total params
537.109   Total estimated model params size (MB)


2746.5621058130055
242922.602724006
FOLD 2
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |                                                                                                    …

[[1171   54]
 [ 113 1190]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.9339398741722107
     ddr-test-aucroc        0.9793624877929688
       ddr-test-f1          0.9344326853752136
      ddr-test-loss         0.17333237826824188
   ddr-test-precision       0.9565916657447815
     ddr-test-recall        0.9132770299911499
  ddr-test-specificity      0.9559183716773987
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |                                                                                                    …

[[ 46 122]
 [  1 347]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7616279125213623
    idrid-test-aucroc       0.9616601467132568
      idrid-test-f1         0.8494492173194885
     idrid-test-loss        1.0118285417556763
  idrid-test-precision      0.7398720979690552
    idrid-test-recall       0.9971264600753784
 idrid-test-specificity     0.2738095223903656
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 3
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | VGG              | 134 M 
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
134 M     Trainable params
0         Non-trainable params
134 M     Total params
537.109   Total estimated model params size (MB)


2724.99033906401
245691.583291351
FOLD 3
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |                                                                                                    …

[[1173   85]
 [  77 1163]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.9351481199264526
     ddr-test-aucroc        0.9817702174186707
       ddr-test-f1          0.9348874688148499
      ddr-test-loss         0.1690412312746048
   ddr-test-precision       0.9318910241127014
     ddr-test-recall        0.9379032254219055
  ddr-test-specificity      0.9324324131011963
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |                                                                                                    …

[[ 35 133]
 [  0 348]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7422480583190918
    idrid-test-aucroc       0.9671763181686401
      idrid-test-f1         0.8395657539367676
     idrid-test-loss         0.978578507900238
  idrid-test-precision      0.7234927415847778
    idrid-test-recall               1.0
 idrid-test-specificity     0.2083333283662796
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 4
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | VGG              | 134 M 
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
134 M     Trainable params
0         Non-trainable params
134 M     Total params
537.109   Total estimated model params size (MB)


2754.6195210059814
248490.160096567
FOLD 4
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |                                                                                                    …

[[1170   95]
 [  45 1184]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.9438652992248535
     ddr-test-aucroc        0.9888440370559692
       ddr-test-f1          0.9441786408424377
      ddr-test-loss         0.15066899359226227
   ddr-test-precision       0.9257231950759888
     ddr-test-recall        0.9633848667144775
  ddr-test-specificity      0.9249011874198914
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: |                                                                                                    …

[[ 36 132]
 [  2 346]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7403100728988647
    idrid-test-aucroc       0.9635758399963379
      idrid-test-f1         0.8377723693847656
     idrid-test-loss        1.6092748641967773
  idrid-test-precision       0.723849356174469
    idrid-test-recall       0.9942528605461121
 idrid-test-specificity     0.2142857164144516
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2703.3201091910014
251236.223690297


### ResNet50 Instanciation

In [6]:
res50_best_weights = models.ResNet50_Weights.DEFAULT
res50_model = models.resnet50(weights=res50_best_weights)
num_ftrs = res50_model.fc.in_features
res50_model.fc = nn.Linear(num_ftrs, num_classes)
res50_preprocess = res50_best_weights.transforms()

In [7]:
res50_preprocess

ImageClassification(
    crop_size=[224]
    resize_size=[232]
    mean=[0.485, 0.456, 0.406]
    std=[0.229, 0.224, 0.225]
    interpolation=InterpolationMode.BILINEAR
)

In [8]:
res50_model.fc 

Linear(in_features=2048, out_features=2, bias=True)

In [23]:
binary_train_and_test(res50_model, 'ResNet50')

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 0 ResNet50
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | ResNet           | 23.5 M
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
23.5 M    Trainable params
0         Non-trainable params
23.5 M    Total params
94.049    Total estimated model params size (MB)


FOLD 0
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


2681.4140807199874


Testing: |                                                                                                    …

[[1053  206]
 [ 119 1130]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc           0.870414674282074
     ddr-test-aucroc        0.9532098770141602
       ddr-test-f1          0.8742746710777283
      ddr-test-loss         0.28664013743400574
   ddr-test-precision       0.8458083868026733
     ddr-test-recall        0.9047237634658813
  ddr-test-specificity      0.8363780975341797
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


259387.978989282


Testing: |                                                                                                    …

[[ 30 138]
 [  0 348]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7325581312179565
    idrid-test-aucroc       0.9385177493095398
      idrid-test-f1         0.8345323801040649
     idrid-test-loss        0.8254213333129883
  idrid-test-precision      0.7160493731498718
    idrid-test-recall               1.0
 idrid-test-specificity     0.1785714328289032
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 1 ResNet50
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | ResNet           | 23.5 M
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
23.5 M    Trainable params
0         Non-trainable params
23.5 M    Total params
94.049    Total estimated model params size (MB)


259401.9331811
FOLD 1
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


2690.4965088779863


Testing: |                                                                                                    …

[[ 982  277]
 [  47 1188]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.8700882196426392
     ddr-test-aucroc        0.9701633453369141
       ddr-test-f1          0.8799999952316284
      ddr-test-loss         0.29429903626441956
   ddr-test-precision       0.8109214901924133
     ddr-test-recall        0.9619433283805847
  ddr-test-specificity      0.7799841165542603
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


262121.816251944


Testing: |                                                                                                    …

[[ 15 153]
 [  0 348]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7034883499145508
    idrid-test-aucroc       0.9227131605148315
      idrid-test-f1         0.8197879791259766
     idrid-test-loss         1.70881187915802
  idrid-test-precision      0.6946107745170593
    idrid-test-recall               1.0
 idrid-test-specificity     0.0892857164144516
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 2 ResNet50
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | ResNet           | 23.5 M
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
23.5 M    Trainable params
0         Non-trainable params
23.5 M    Total params
94.049    Total estimated model params size (MB)


262135.799952848
FOLD 2
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


2680.8203076309874


Testing: |                                                                                                    …

[[1084  141]
 [ 114 1189]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.8991297483444214
     ddr-test-aucroc         0.969192624092102
       ddr-test-f1          0.9031522870063782
      ddr-test-loss         0.2387256622314453
   ddr-test-precision       0.8939849734306335
     ddr-test-recall        0.9125096201896667
  ddr-test-specificity      0.8848979473114014
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


264846.555163271


Testing: |                                                                                                    …

[[ 19 149]
 [  1 347]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7093023061752319
    idrid-test-aucroc       0.9260997772216797
      idrid-test-f1         0.8222748637199402
     idrid-test-loss        1.7960588932037354
  idrid-test-precision      0.6995967626571655
    idrid-test-recall       0.9971264600753784
 idrid-test-specificity     0.1130952388048172
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 3 ResNet50
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | ResNet           | 23.5 M
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
23.5 M    Trainable params
0         Non-trainable params
23.5 M    Total params
94.049    Total estimated model params size (MB)


264860.92672301
FOLD 3
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


2725.7419248609804


Testing: |                                                                                                    …

[[1195   63]
 [  91 1149]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.9383506774902344
     ddr-test-aucroc        0.9871442317962646
       ddr-test-f1          0.9371941089630127
      ddr-test-loss         0.14746901392936707
   ddr-test-precision        0.948019802570343
     ddr-test-recall         0.926612913608551
  ddr-test-specificity      0.9499205350875854
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


267615.912580583


Testing: |                                                                                                    …

[[ 32 136]
 [  4 344]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7286821603775024
    idrid-test-aucroc       0.9330955743789673
      idrid-test-f1         0.8309178948402405
     idrid-test-loss        1.3040125370025635
  idrid-test-precision      0.7166666388511658
    idrid-test-recall       0.9885057210922241
 idrid-test-specificity      0.190476194024086
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 4 ResNet50
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | ResNet           | 23.5 M
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
23.5 M    Trainable params
0         Non-trainable params
23.5 M    Total params
94.049    Total estimated model params size (MB)


267630.138369322
FOLD 4
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


2655.0580234280205


Testing: |                                                                                                    …

[[1227   38]
 [  69 1160]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc           0.957097053527832
     ddr-test-aucroc        0.9918677806854248
       ddr-test-f1          0.9559126496315002
      ddr-test-loss         0.12521512806415558
   ddr-test-precision       0.9682804942131042
     ddr-test-recall        0.9438567757606506
  ddr-test-specificity      0.9699604511260986
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


270314.651294326


Testing: |                                                                                                    …

[[ 25 143]
 [  0 348]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7228682041168213
    idrid-test-aucroc       0.9378848075866699
      idrid-test-f1         0.8295590281486511
     idrid-test-loss         2.096717119216919
  idrid-test-precision      0.7087576389312744
    idrid-test-recall               1.0
 idrid-test-specificity     0.1488095223903656
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
270328.542583761


### MobileNet v2 Instanciation

In [5]:
mobi_best_weights = models.MobileNet_V2_Weights.DEFAULT
mobi_model = models.mobilenet_v2(weights=mobi_best_weights)
mobi_preprocess = mobi_best_weights.transforms()
num_ftrs = mobi_model.classifier[-1].in_features
mobi_model.classifier[-1] = nn.Linear(num_ftrs, num_classes)

In [7]:
binary_train_and_test(mobi_model, 'MobileNetV2')

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 0 MobileNetV2
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | MobileNetV2      | 2.2 M 
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
2.2 M     Trainable params
0         Non-trainable params
2.2 M     Total params
8.906     Total estimated model params size (MB)


FOLD 0
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


2672.32289527799


Testing: |                                                                                                    …

[[1204   55]
 [ 246 1003]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.8799840807914734
     ddr-test-aucroc        0.9596633911132812
       ddr-test-f1          0.8695275187492371
      ddr-test-loss         0.35383737087249756
   ddr-test-precision       0.9480150938034058
     ddr-test-recall        0.8030424118041992
  ddr-test-specificity      0.9563145637512207
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


273331.016548681


Testing: |                                                                                                    …

GPU available: True (cuda), used: True


[[ 64 104]
 [  6 342]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc          0.786821722984314
    idrid-test-aucroc       0.9233630895614624
      idrid-test-f1         0.8614609837532043
     idrid-test-loss        0.7273833155632019
  idrid-test-precision      0.7668161392211914
    idrid-test-recall        0.982758641242981
 idrid-test-specificity      0.380952388048172
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
273344.262185499
FOLD 1
--------------------------------


TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 1 MobileNetV2
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | MobileNetV2      | 2.2 M 
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
2.2 M     Trainable params
0         Non-trainable params
2.2 M     Total params
8.906     Total estimated model params size (MB)


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


2653.7009319129866


Testing: |                                                                                                    …

[[1067  192]
 [  77 1158]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.8921411633491516
     ddr-test-aucroc        0.9684564471244812
       ddr-test-f1          0.8959380984306335
      ddr-test-loss         0.27279436588287354
   ddr-test-precision       0.8577777743339539
     ddr-test-recall        0.9376518130302429
  ddr-test-specificity      0.8474979996681213
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


276026.18574238


Testing: |                                                                                                    …

[[ 75  93]
 [  7 341]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.8062015771865845
    idrid-test-aucroc       0.9438371658325195
      idrid-test-f1         0.8721227645874023
     idrid-test-loss        0.7954339385032654
  idrid-test-precision      0.7857142686843872
    idrid-test-recall       0.9798850417137146
 idrid-test-specificity     0.4464285671710968
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 2 MobileNetV2
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | MobileNetV2      | 2.2 M 
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
2.2 M     Trainable params
0         Non-trainable params
2.2 M     Total params
8.906     Total estimated model params size (MB)


276039.942710122
FOLD 2
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


2646.131647660979


Testing: |                                                                                                    …

[[1005  220]
 [  29 1274]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.9015031456947327
     ddr-test-aucroc        0.9846251010894775
       ddr-test-f1          0.9109760522842407
      ddr-test-loss         0.2500293254852295
   ddr-test-precision       0.8527442812919617
     ddr-test-recall        0.9777436852455139
  ddr-test-specificity      0.8204081654548645
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


278713.87463981


Testing: |                                                                                                    …

[[ 18 150]
 [  0 348]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7093023061752319
    idrid-test-aucroc       0.9446753263473511
      idrid-test-f1         0.8226950168609619
     idrid-test-loss        1.7486761808395386
  idrid-test-precision      0.6987951993942261
    idrid-test-recall               1.0
 idrid-test-specificity     0.1071428582072258
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 3 MobileNetV2
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | MobileNetV2      | 2.2 M 
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
2.2 M     Trainable params
0         Non-trainable params
2.2 M     Total params
8.906     Total estimated model params size (MB)


278727.289391898
FOLD 3
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


2652.502848853008


Testing: |                                                                                                    …

[[1211   47]
 [  76 1164]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.9507606029510498
     ddr-test-aucroc        0.9896360039710999
       ddr-test-f1          0.9498164057731628
      ddr-test-loss         0.1404801905155182
   ddr-test-precision       0.9611890912055969
     ddr-test-recall        0.9387096762657166
  ddr-test-specificity      0.9626390933990479
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


281407.90371127


Testing: |                                                                                                    …

[[ 68 100]
 [  9 339]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc          0.788759708404541
    idrid-test-aucroc       0.9337626695632935
      idrid-test-f1         0.8614993691444397
     idrid-test-loss          1.2382732629776
  idrid-test-precision      0.7722095847129822
    idrid-test-recall       0.9741379022598267
 idrid-test-specificity     0.4047619104385376
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ./checkpoints_kfold/tb_logs/FOLD 4 MobileNetV2
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | MobileNetV2      | 2.2 M 
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
2.2 M     Trainable params
0         Non-trainable params
2.2 M     Total params
8.906     Total estimated model params size (MB)


281422.003874618
FOLD 4
--------------------------------


Training: |                                                                                                   …

`Trainer.fit` stopped: `max_epochs=25` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


2659.6930846429896


Testing: |                                                                                                    …

[[1227   38]
 [  66 1163]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      ddr-test-acc          0.9582999348640442
     ddr-test-aucroc        0.9942869544029236
       ddr-test-f1          0.9572016596794128
      ddr-test-loss         0.10830139368772507
   ddr-test-precision       0.9683597087860107
     ddr-test-recall         0.946297824382782
  ddr-test-specificity      0.9699604511260986
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


284109.854408468


Testing: |                                                                                                    …

[[ 48 120]
 [  6 342]]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     idrid-test-acc         0.7558139562606812
    idrid-test-aucroc       0.9222171306610107
      idrid-test-f1         0.8444444537162781
     idrid-test-loss        1.6882370710372925
  idrid-test-precision      0.7402597665786743
    idrid-test-recall        0.982758641242981
 idrid-test-specificity     0.2857142984867096
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
284123.81001955


### EfficientNetB7 INstanciation

In [4]:
effcb7_best_weights = models.EfficientNet_B7_Weights.DEFAULT
effcb7_model = models.efficientnet_b7(weights=effcb7_best_weights)
effcb7_preprocess = effcb7_best_weights.transforms()
num_ftrs = effcb7_model.classifier[-1].in_features
effcb7_model.classifier[-1] = nn.Linear(num_ftrs, num_classes)

In [5]:
binary_train_and_test(effcb7_model, 'EfficientNetB7')

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | EfficientNet     | 63.8 M
1 | loss_module   | CrossEntropyLoss | 0     
2 | metrics_train | MetricCollection | 0     
3 | metrics_test  | MetricCollection | 0     
---------------------------------------------------
63.8 M    Trainable params
0         Non-trainable params
63.8 M    Total params
255.168   Total estimated model params size (MB)


FOLD 0
--------------------------------


Training: |                                                                                                   …

OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacity of 11.72 GiB of which 37.50 MiB is free. Including non-PyTorch memory, this process has 11.33 GiB memory in use. Of the allocated memory 10.74 GiB is allocated by PyTorch, and 368.88 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

### EfficientNetV2-L INstanciation

In [4]:
effcv2l_best_weights = models.EfficientNet_V2_L_Weights.DEFAULT
effcv2l_model = models.efficientnet_v2_l(weights=effcv2l_best_weights)
effcv2l_preprocess = effcv2l_best_weights.transforms()
num_ftrs = effcv2l_model.classifier[-1].in_features
effcv2l_model.classifier[-1] = nn.Linear(num_ftrs, num_classes)

In [5]:
effcv2l_preprocess

ImageClassification(
    crop_size=[480]
    resize_size=[480]
    mean=[0.5, 0.5, 0.5]
    std=[0.5, 0.5, 0.5]
    interpolation=InterpolationMode.BICUBIC
)

In [6]:
effcv2l_model.classifier

Sequential(
  (0): Dropout(p=0.4, inplace=True)
  (1): Linear(in_features=1280, out_features=2, bias=True)
)

In [7]:
binary_train_and_test(effcv2l_model, 'EfficientNetV2-L')

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


FOLD 0
--------------------------------


OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 11.72 GiB of which 17.19 MiB is free. Process 689449 has 11.11 GiB memory in use. Including non-PyTorch memory, this process has 290.00 MiB memory in use. Of the allocated memory 93.23 MiB is allocated by PyTorch, and 4.77 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)